<#import "*/gen-options.ftl" as opt>
package ${opt.entityPackage};

<#assign entityName = tableName?replace("_", " ")?capitalize?replace(" ", "") />

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;
import org.hibernate.validator.Length;
import org.jboss.seam.Component;
import org.jboss.seam.annotations.In;
import org.jboss.seam.contexts.Contexts;
import org.jboss.seam.security.Credentials;
import org.jboss.seam.security.Identity;

/**
 * ${entityName} generated by Generality
 */
@Entity
@Table(name = "${tableName}"<#if tableSchema??>, schema = "${tableSchema!}"</#if>)
public class ${entityName} implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

<#assign attrNames = "" />
<#list columns as column>
  <#assign javatype = opt.insertJavaType(column) />
  <#assign attrname = opt.mixedCase(column) />
  <#if !column.primaryKey>
	<#assign fk = opt.getFk(column) />
	<#if (fk?size > 0)>
		<#list tables as t>
			<#if t.tableName == fk.pktableName>
				<#assign javatype = opt.camelCaseStr(fk.pktableName) />
				<#if !opt.attributesFromColumnNames>
					<#assign attrname = opt.mixedCaseStr(fk.pktableName) />
				</#if>
				<#break />
			</#if>
		</#list>
	</#if>
  </#if>
  <#assign res = attrNames?matches(attrname)?size />
  <#assign attrNames = attrNames + " " + attrname />
  <#if res &gt; 0>
    <#assign attrname = attrname + res />
  </#if>
	private ${javatype} ${attrname};
</#list>
<@opt.master_detail ; detailEntity>
	private List<${detailEntity}> ${detailEntity?uncap_first}s = new Vector<${detailEntity}>();
</@opt.master_detail>

	public ${entityName}() {
	}

	public ${entityName}(${opt.insertJavaType(opt.keyColumn)} ${opt.mixedCase(opt.keyColumn)}) {
		this.${opt.mixedCase(opt.keyColumn)} = ${opt.mixedCase(opt.keyColumn)};
	}

<#assign attrNames = "" />	
<#list columns as column>
  <#assign javatype = opt.insertJavaType(column) />
  <#assign attrname = opt.mixedCase(column) />
  <#if opt.keyColumn == column>
  	<#if opt.useSequencesForIds>
	@Id
	@GeneratedValue(generator="${tableName?upper_case}_GENERATOR")
	@SequenceGenerator(name="${tableName?upper_case}_GENERATOR",sequenceName="<#if tableSchema??>${tableSchema!}.</#if>${tableName}_${opt.keyColumn.columnName}_seq")
	<#else>
	@Id
/*	@GeneratedValue(generator="${tableName?upper_case}_GENERATOR")
	@SequenceGenerator(name="${tableName?upper_case}_GENERATOR",sequenceName="<#if tableSchema??>${tableSchema!}.</#if>${tableName}_${opt.keyColumn.columnName}_seq")*/
	</#if>
  </#if>
  <#if !column.primaryKey>
	<#assign fk = opt.getFk(column) />
	<#if (fk?size > 0)>
		<#assign itemGenerated = false />
		<#list tables as t>
			<#if t.tableName == fk.pktableName>
				<#assign itemGenerated = true />
				<#assign javatype = opt.camelCaseStr(fk.pktableName) />
				<#if !opt.attributesFromColumnNames>
				  <#assign attrname = opt.mixedCaseStr(fk.pktableName) />
				</#if>
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "${column.columnName}")
				<#break />
			</#if>
		</#list>
		<#if !itemGenerated>
<@opt.insertColumnAnnotation column />
		</#if>
	<#else>
<@opt.insertColumnAnnotation column />
	</#if>
  <#else>
<@opt.insertColumnAnnotation column />
  </#if>
  <#assign res = attrNames?matches(attrname)?size />
  <#assign attrNames = attrNames + " " + attrname />
  <#if res &gt; 0>
    <#assign attrname = attrname + res />
  </#if>
	public ${javatype} get${attrname?cap_first}() {
		return this.${attrname};
	}

	public void set${attrname?cap_first}(${javatype} ${attrname}) {
		this.${attrname} = ${attrname};
	}
	
</#list>
<@opt.master_detail ; detailEntity>
	<#assign detailAttr = detailEntity?uncap_first + "s" />
	@OneToMany(mappedBy="${opt.mixedCaseStr(tableName)}", fetch=FetchType.LAZY, cascade=CascadeType.ALL)
	@Cascade({org.hibernate.annotations.CascadeType.ALL, org.hibernate.annotations.CascadeType.DELETE_ORPHAN})
	public List<${detailEntity}> get${detailAttr?cap_first}() {
		return this.${detailAttr};
	}

	public void set${detailAttr?cap_first}(List<${detailEntity}> ${detailAttr}) {
		this.${detailAttr} = ${detailAttr};
	}
	
</@opt.master_detail>
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((${opt.mixedCase(opt.keyColumn)} == null) ? 0 : ${opt.mixedCase(opt.keyColumn)}.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		${entityName} other = (${entityName}) obj;
		if (${opt.mixedCase(opt.keyColumn)} == null) {
			if (other.${opt.mixedCase(opt.keyColumn)} != null)
				return false;
		} else if (!${opt.mixedCase(opt.keyColumn)}.equals(other.${opt.mixedCase(opt.keyColumn)}))
			return false;
		return true;
	}
}
